### PR TITLE
ImageNav API Fixes

### PR DESCRIPTION
**Pull request by jacobkrantz**
## Motivation and Context

Since ImageNav was added to Home-Robot (#87), the `Categorical2DSemanticMapModule` and `DiscretePlanner` have received breaking changes. Resulting API issues pertaining to ImageNav were cataloged in issue #182. This PR aims to restore the functionality of the ImageNav project by fixing these API issues.

## Changelog

Missing config and API entries have been added to restore the functionality of the ImageNav demo. Values were chosen to maintain alignment with the ObjectNav project's use of mapping + planning.

## How Has This Been Tested

I was able to successfully run the simulation demo:
```bash
cd projects/instanceimagenav
python eval_episode_habitat.py
```

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

# Checklist:

- [ ] I have made changes to existing documentation where needed.
- [ ] I have added tests that show that the PR is functional.
- [ ] I ran `tests/hw_manual_test.py` on hardware and observed that robot behavior looks normal.

### CODE REVIEW

**Review by cpaxton — COMMENTED** [review]
Any thoughts on adding a test for imagenav agent so it does not break in the future?

**Comment by cpaxton** [comment]
It could be a very simple one, just move and take a few steps in ReplicaCad

**Comment by jacobkrantz** [comment]
This concern is relevant to all agents in https://github.com/facebookresearch/home-robot/tree/main/src/home_robot/home_robot/agent. I wonder if there is a way to unify their testing. Each agent relies on a unique config and simulation environment so this could be challenging.

**Comment by yvsriram** [comment]
Yes, I unifying tests can be tricky. I will be pushing a test for ovmm_agent today. 

@cpaxton I am not sure if we have ImageNav episodes for ReplicaCAD.

**Review by cpaxton — APPROVED** [review]
Given that there are no imagenav episodes for replica cad, and @yvsriram  is pushing a test separately, I think this LGTM

**Pull request merged**
